### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError: Session was not created with a graph before Run()!

### ISSUE THREAD

**Issue by ahaqxjl** [srebuffi/iCaRL#13]
I met this error while running training code via python main_resnet_tf.py.

tensorflow.python.framework.errors_impl.InvalidArgumentError: Session was not created with a graph before Run()!

Traceback (most recent call last):
  File "main_resnet_tf.py", line 159, in <module>
    sess.run(tf.global_variables_initializer())

Running environment:
Python 3.6.13
Tensorflow 1.1.0
scipy 0.19.1
cuda 11.4

Maybe too much time past after code released, I am looking forward someone help me. Thanks a lot. @srebuffi

**Comment by srebuffi** [comment]
Sorry for the late reply! Yes, I released the code 4 years ago so Tensorflow changed a lot since then. I would advise to use more recent re-implementations of the paper in other repos.

**Comment by ahaqxjl** [comment]
@srebuffi Thanks a lot. I found re-implementation in "Three scenarios for continual learning" and it works.
